name: Test and Build

on:
  push:
    paths-ignore:
      - README

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: amd64

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: go mod tidy
        run: go mod tidy -x

      - name: go test
        run: go test -v ./...

      - name: go build
        run: go build -o bin/dimm-${GITHUB_SHA::7}-$GOOS-$GOARCH ./cmd/dimm

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/*
