name: Test and Build

on:
  push:
    paths-ignore:
      - README

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: go mod tidy
        run: go mod tidy -x

      - name: go test
        run: go test -p 1 -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        cmd: [funky-orca]
        go-os: [linux]
        go-arch: [amd64, arm64]

    env:
      GOOS: linux
      GOARCH: amd64

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: go mod tidy
        run: go mod tidy -x

      - name: go build
        run: go build -o bin/$CMD-${GITHUB_SHA::7}-$GOOS-$GOARCH ./cmd/$CMD
        env:
          CMD: ${{ matrix.cmd }}
          GOOS: ${{ matrix.go-os }}
          GOARCH: ${{ matrix.go-arch }}

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: bin/*
